sudo: required
language: bash
services:
  - docker
install:
  - bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.install
script:
  - bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.script
after_failure:
  - bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.after_failure
after_success:
  - bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.after_success
